meta/conf/layer.conf

Add signing-key layer to LAYERDEPENDS to fix the below yocto compliance issue:
INFO: ERROR: test_world (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 58, in test_world
get_signatures(self.td['builddir'], failsafe=False)
File "/build/layers/oe-core/scripts/lib/checklayer/__init__.py", line 315, in get_signatures
check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
File "/build/layers/oe-core/scripts/lib/checklayer/__init__.py", line 287, in check_command
raise RuntimeError(msg)
RuntimeError: Generating signatures failed. This might be due to some …

meta: add signing-key to LAYERDEPENDS

---

meta-tpm2/recipes-tpm/tpm2-tools/files/0001-tests-switch-to-python3.patch
meta-tpm2/recipes-tpm/tpm2-tools/tpm2-tools_5.5.bb

There is no python symblic link by default on system which will cause an error when running test scripts on target:
$ ./test_tpm2_activecredential.sh: line 66: python: command not found
So drop python2 support and only keep python3.

tpm2-tools: only support python3 in test scripts

---

meta-signing-key/recipes-devtools/sbsigntool/sbsigntool/0001-create-ccan-tree-use-native-tools.patch
meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_git.bb

Hi all,
as mentioned in the commit message I am hitting a bug when cross compiling `sbsigntool`. Tools compiled during the configuration stage and used on the host  have the interpreter set wrong. It points to the target interpreter which doesn't exist on the host. Even if I were to manually patch the elf to point to the correct interpreter (patchelf), I assume that the binaries compiled with the target compilation arguments may not even run correctly on the host since I'm compiling for a zen3 AMD processor from an intel CPU.
The proposed solution feels a bit hackish since I'm manually copying the tools into the build directory... a simpler solution may exist.
Best,
Guillaume

sbsigntool: fix cross compilation flags contamination

---

meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb

Fixes:
ERROR: shim_git.bb: Unable to get checksum for shim SRC_URI entry shimEFI_ARCH.efi.signed: file could not be found

shim: fix expansion for EFI_ARCH

---

meta-integrity/recipes-support/ima-inspect/files/0001-ima_helpers-add-missing-stdint.h-include.patch
meta-integrity/recipes-support/ima-inspect/ima-inspect_0.13.bb

Backport patch [1] to fix the below build failure:
| In file included from ../git/src/ima_helpers.cxx:12:
| ../git/src/ima_helpers.hxx:17:27: error: 'uint8_t' does not name a type
| 17 |         HexDumpData(const uint8_t *data, size_t bytes)
[1] https://github.com/mgerstner/ima-inspect/commit/9a75001d7d20c56d65d4f197a7ec10aae26949c5

ima-inspect: add missing stdint.h include

---

meta-signing-key/recipes-devtools/sbsigntool/sbsigntool_0.9.5.bb

Set COMPATIBLE_HOST for sbsigntool in accord with its dependency gnu-efi.

sbsigntool: set COMPATIBLE_HOST

---

meta-signing-key/recipes-devtools/pesign/pesign/0001-src-Makefile-disable-build-manpage.patch
meta-signing-key/recipes-devtools/pesign/pesign_git.bb

Pesign is a signing tools for PE-COFF binaries. Compliant with the PE and Authenticode specifications.

pesign: add recipe

---

meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc
meta-efi-secure-boot/recipes-bsp/efitools/efitools/0001-Make.rules-Pass-CFLAGS-to-Makefile.patch

It ensures right debug directory remapping options are passed to compiler.
Fixes:
WARNING: efitools-1.9.2-r0 do_package_qa: QA Issue: File /usr/bin/.debug/efi-updatevar in package efitools-dbg contains reference to TMPDIR
File /usr/bin/.debug/sig-list-to-certs in package efitools-dbg contains reference to TMPDIR
File /usr/bin/.debug/efi-readvar in package efitools-dbg contains reference to TMPDIR
File /usr/bin/.debug/hash-to-efi-sig-list in package efitools-dbg contains reference to TMPDIR
File /usr/bin/.debug/cert-to-efi-sig-list in package efitools-dbg contains reference to TMPDIR
File /usr/bin/.debug/sign-efi-sig-list in package efitools-dbg contains reference to TMPDIR
File /usr/bin/.debug/cert-to-efi-hash-list in package efitools-dbg contains reference to TMPDIR
File …

efitools: Pass CFLAGS to make

---

meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc

Efitools are compatible with aarch64 machines, this should be added to build efitools correctly.

efitools: Add aarch64 as a COMPATIBLE_HOST

---

meta-efi-secure-boot/conf/layer.conf
meta-encrypted-storage/conf/layer.conf
meta-ids/conf/layer.conf
meta-integrity/conf/layer.conf
meta-intel-sgx/conf/layer.conf
meta-signing-key/conf/layer.conf
meta-tpm/conf/layer.conf
meta-tpm2/conf/layer.conf
meta/conf/layer.conf

oe-core has switched to nanbield in:
https://git.openembedded.org/openembedded-core/commit/?id=f212cb12a0db9c9de5afd3cc89b1331d386e55f6

layer.conf: update LAYERSERIES_COMPAT for nanbield

---

meta-efi-secure-boot/recipes-bsp/grub/grub-efi/sbat.csv

Due to CVE-2023-4692 and CVE-2023-4693 GRUB2 vulnerabilities described at https://lists.gnu.org/archive/html/grub-devel/2023-10/msg00028.html, it's been agreed to update the required GRUB2 SBAT global generation number in its binaries to 4:
https://github.com/rhboot/shim-review/pull/348
This commit changes the aforementioned number from 3 to 4.

Update GRUB2 SBAT global generation number to 4

---

meta-efi-secure-boot/recipes-bsp/seloader/seloader_git.bb
meta-efi-secure-boot/recipes-extended/mokutil/mokutil_git.bb
meta-encrypted-storage/recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
meta-ids/recipes-ids/mtree/mtree_git.bb
meta-signing-key/recipes-devtools/libsign/libsign_git.bb
meta-signing-key/recipes-devtools/pesign/pesign_git.bb
meta-tpm/recipes-tpm/pcr-extend/pcr-extend_git.bb
meta-tpm/recipes-tpm/tpm-quote-tools/tpm-quote-tools_git.bb
meta-tpm/recipes-tpm/tss-testsuite/tss-testsuite_git.bb

Drop SRCPV as this variable is no longer needed in PV[1].
[1] https://git.openembedded.org/openembedded-core/commit/?id=a8e7b0f932b9ea69b3a218fca18041676c65aba0

recipes: drop ${SRCPV} usage

---

meta-tpm2/recipes-tpm/tpm2-tools/tpm2-tools_5.7.bb

tpm2-tools: upgrade 5.6 -> 5.7
Include Security fixes:
Fixed CVE-2024-29038
Fixed CVE-2024-29039
Changelog:
https://github.com/tpm2-software/tpm2-tools/releases/tag/5.7

tpm2-tools: upgrade 5.6 -> 5.7

---

meta-encrypted-storage/recipes-kernel/linux/linux-yocto-dev.bbappend
meta-encrypted-storage/recipes-kernel/linux/linux-yocto-rt_%.bbappend

linux-yocto-luks.inc is shared among linux-yocto, linux-yocto-rt and linux-yocto-dev and cannot be found with ${BPN} in the latter two.
ERROR: ParseError at layers/meta-secure-core/meta-encrypted-storage/recipes-kernel/linux/linux-yocto-dev.bbappend:1: Could not include required file linux-yocto-dev-luks.inc ERROR: ParseError at layers/meta-secure-core/meta-encrypted-storage/recipes-kernel/linux/linux-yocto-rt_%.bbappend:1: Could not include required file linux-yocto-rt-luks.inc

meta-encrypted-storage: fix failure to find linux-yocto-luks.inc

---

meta-efi-secure-boot/recipes-bsp/shim/shim_15.8.bb

vendor_dbx.esl is only built if SIGNING_MODEL=='user' and MOK_SB=='1', but it's inclusion in shim's EXTRA_OEMAKE is only guarded by SIGNING_MODEL.
Fixes #57

Fix conditions for vendor_dbx.esl in shim

---

meta-tpm2/recipes-tpm/tpm2-tss/tpm2-tss_4.1.3.bb

The libgcrypt ESYS crypto backend has been removed since 3.0.0[1]. Remove libgcrypt from DEPENDS and RDEPENDS.
[1] https://github.com/tpm2-software/tpm2-tss/releases/tag/3.0.0

tpm2-tss: drop libgcrypt dependency

---

meta-efi-secure-boot/recipes-bsp/shim/shim_git.bb

There is a do_rootfs error in secure-core-image when UEFI_SB = 1 and MOK_SB = 0:
Error: Transaction test error:
file /boot/efi/EFI/BOOT/bootx64.efi conflicts between attempted installs of seloader-0.4.6+git0+8b90f76a8d-r0.core2_64 and shim-15.8-r0.core2_64
When MOK_SB=0, SELoader will become the first stage loader and SELoader.efi will be renamed to bootx64.efi. This will conflict with bootx64.efi in shim.
To avoid this conflict, install shimx64.efi instead of bootx64.efi in shim if MOK_SB=0
Fixes: #64

shim: install shim.efi instead of boot.efi if MOK_SB=0

---

meta-integrity/classes/ima-evm-rootfs.bbclass

The image-mklibs.bbclass and image-prelink.bbclass have been removed in commits[1][2].
[1] https://git.openembedded.org/openembedded-core/commit/?id=908df863b419d1cad7317153101fc827e7e3a354
[2] https://git.openembedded.org/openembedded-core/commit/?id=857baaf9e3d181ca18264e85d90b899fd94acff9

ima-evm-rootfs.bbclass: remove references to mklibs and prelink

---

meta-signing-key/recipes-devtools/gen-sbkeys/gen-sbkeys.bb
meta-signing-key/recipes-devtools/gen-sbkeys/gen-sbkeys/gen_sbkeys.sh

Generate keys that can be used to sign EFI binaries.
The keys will be stored in the SBSIGN_KEYS_DIR directory, and if they are already there, new keys will not be generated to keep build reproducibility.
Originally, this change was submitted to meta-arm to enable Secure Boot, but as it's using efitools, it's more appropriate to add it to meta-secure-core.

Add gen-sbkeys.bb recipe

---

meta-encrypted-storage/README.md

The luks-setup.sh is renamed to luks-setup in cryptfs-tpm2[1]. Update README.md to adapt this change.
[1] https://github.com/jiazhang0/cryptfs-tpm2/commit/820c4947787e436c8d30dbb37ef5f1feedbc2585

meta-encrypted-storage/README.md: update

---

meta-efi-secure-boot/recipes-bsp/efitools/efitools-native_1.9.2.bb
meta-efi-secure-boot/recipes-bsp/efitools/efitools.inc
meta-efi-secure-boot/recipes-bsp/efitools/efitools/0001-add-binary-only-make-rules.patch

The native build of efitools is only needed for the tools, add a patch so that we can just build and install the tools.
This means we don't need to depend on gnu-efi-native anymore, and also the native recipe doesn't end up shipping a build-host-targetting LockDown.efi in the sysroot which is obviously incorrect.
(note that I've not tested this on hardware, but the build appears to work)

efitools: improve the native build

---

meta-efi-secure-boot/recipes-kernel/linux/linux-yocto-efi-secure-boot.inc

There is a do_sign_bundled_kernel in kernel build when UEFI_SELOADER = 0 and GRUB_SIGN_VERIFY = 1:
Error: Failed to sign error:
file /boot/bzImage.initramfs fails to be signed within do_sign_bundled_kernel function
When do_sign_bundled_kernel is called there is no access to deployed keys within boot_sign as gpg_path is empty, thus check_deploy_keys and check_boot_public_key are being added into do_sign_bundled_kernel[prefuncs]
Fixes: #85

linux-yocto-efi-secure-boot.inc: fix missing prefuncs

---

README

After rpm was updated to 4.20, rpm signing support has been disabled by default in oe-core[1]. This is because the internal openpgp parser was removed in rpm 4.20, and its replacement rpm-sequoia[2] requires clang and rust. The oe-core can't force both rust and clang into the default build dependency chain[3].
For feature ima, we skip signing the files in rpm package by not inheriting sign_rpm_ext class and sign all files during do_image via ima-evm-rootfs class.
[1] https://git.openembedded.org/openembedded-core/commit/?id=8c15b4577d5e554cc2dd5adfb88b816894b05a9a
[2] https://github.com/rpm-software-management/rpm-sequoia/
[3] https://lists.openembedded.org/g/openembedded-architecture/topic/102780086

README: do not inherit sign_rpm_ext class for ima feature

---

README
meta-integrity/recipes-devtools/rpm/rpm-integrity.inc

Since rpm-sequoia was added to oe-core[1], rpm signing support has been restored. So we can re-inherit sign_rpm_ext class in ima feautre.
[1] https://git.openembedded.org/openembedded-core/commit/?id=d8b01b436d37f4deb2de5d234e8f04c957719ca3

rpm: enable sequoia packageconfig for ima feature

---

meta-tpm2/recipes-tpm/tpm2-openssl/tpm2-openssl_1.3.0.bb

ChangeLog:
https://github.com/tpm2-software/tpm2-openssl/releases/tag/1.3.0
License-Update: Updated copyright years

tpm2-openssl: upgrade 1.2.0 -> 1.3.0

---

meta-signing-key/classes/user-key-store.bbclass

Got this error while building on my CI system (using docker and debian 12.8):
ERROR: linux-6.1.68+git-r0 do_sign: ExecutionError('/builds/.../tmp/work/linux/6.1.68+git/temp/run.deploy_uefi_sb_keys.903779', 1, None, None)
ERROR: Logfile of failure stored in: /builds/.../tmp/work/machine-eko-linux/linux/6.1.68+git/temp/log.do_sign.903779
| DEBUG: Executing python function check_deploy_keys
| DEBUG: Executing shell function deploy_uefi_sb_keys
| cp: failed to preserve ownership for '/builds/.../tmp/deploy/images/machine/sample-keys/uefi_sb_keys/DB.crt': Invalid argument
| cp: failed to preserve ownership for '/builds/.../tmp/deploy/images/machine/sample-keys/uefi_sb_keys/DB.key': Invalid argument
| cp: failed to preserve ownership for …

user-key-store: do not preserve key file ownership when deploying

---

meta-tpm2/recipes-tpm/tpm2-abrmd/tpm2-abrmd_3.0.0.bb

Fixes:
WARNING: tpm2-abrmd_3.0.0.bb:34 has a lack of whitespace around the assignment:
'PACKAGECONFIG ??="${@bb.utils.contains('DISTRO_FEATURES','systemd','systemd', '', d)}"'

tpm2-abrmd: fix variable assignment whitespace

---

meta-integrity/recipes-support/ima-evm-utils/ima-evm-utils_1.5.bb

Forcibly disable manpage build.
Since external tools are required to build the man pages, we don't need them anyway.

ima-evm-utils: disable manpage build
